const SHOPIFY_API_LIST = "service/SHOPIFY_API_LIST";
const SHOPIFY_ADD_CART_LIST = "cart/SHOPIFY_ADD_CART_LIST";
const SHOPIFY_REMOVE_CART_LIST = "cart/SHOPIFY_REMOVE_CART_LIST";

export { SHOPIFY_API_LIST, SHOPIFY_ADD_CART_LIST, SHOPIFY_REMOVE_CART_LIST };
